# Generated by Django 4.1.5 on 2023-01-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_profile_other_skills'),
        ('Home', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('is_read', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default='No subject', max_length=100)),
                ('msg', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='User.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='User.profile')),
            ],
        ),
    ]
