# Generated by Django 4.1.5 on 2023-01-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_new_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_msg',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
