# Generated by Django 4.1.5 on 2023-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_new_msg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
