# Generated by Django 4.1.5 on 2023-01-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile_forgot_password_token'),
        ('Home', '0006_project_no_of_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.project')),
            ],
        ),
    ]
