# Generated by Django 4.1.5 on 2023-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_test_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
