# Generated by Django 4.1.5 on 2023-01-06 04:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/avatars/default.jpg', upload_to='avatars')),
                ('summary', models.TextField(default='New user on our platform!', verbose_name='Summary about user')),
                ('location', models.TextField(default='Location is not specified.', verbose_name='Place of residence')),
                ('about', models.TextField(default='Apparently, this user prefers to keep an air of mystery about them.', verbose_name='About')),
                ('other_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, verbose_name='Other skills'), null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
