# Generated by Django 4.1.5 on 2023-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other_skills',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
