# Generated by Django 4.1.5 on 2023-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_profile_other_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other_skills',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
